# Generated by Django 4.0.1 on 2022-03-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_options_address_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='电子邮箱'),
        ),
    ]
