# Generated by Django 4.0.1 on 2022-03-15 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('users', '0003_address_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='county',
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses_by_district', to='areas.area', verbose_name='区'),
        ),
    ]
