# Generated by Django 4.0.1 on 2022-02-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skuspecification',
            table='myshop_sku_specification',
        ),
    ]
