# Generated by Django 4.0.1 on 2022-02-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goodschannelgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['id'], 'verbose_name': 'SPU', 'verbose_name_plural': 'SPU'},
        ),
        migrations.AddField(
            model_name='goods',
            name='desc_pack',
            field=models.TextField(default='', verbose_name='包装信息'),
        ),
        migrations.AddField(
            model_name='goods',
            name='desc_service',
            field=models.TextField(default='', verbose_name='售后服务'),
        ),
        migrations.AlterModelTable(
            name='goods',
            table='myshop_spu',
        ),
    ]
