# Generated by Django 4.0.1 on 2022-02-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_goods_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='desc_detail',
            field=models.TextField(default='', verbose_name='详细介绍'),
        ),
    ]
