# Generated by Django 4.0.1 on 2022-03-11 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_sku_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='goods.goodscategory', verbose_name='父类别'),
        ),
        migrations.AlterField(
            model_name='goodsspecification',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='goods.goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='goods.goods', verbose_name='所属商品'),
        ),
        migrations.AlterField(
            model_name='skuspecification',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='goods.sku', verbose_name='sku'),
        ),
        migrations.AlterField(
            model_name='specificationoption',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='goods.goodsspecification', verbose_name='规格'),
        ),
    ]
