# Generated by Django 4.0.1 on 2022-03-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_alter_sku_default_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='default_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='商品默认图片'),
        ),
    ]
