# Generated by Django 4.0.1 on 2022-02-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_goods_options_goods_desc_pack_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='myshop_goods',
        ),
    ]
