# Generated by Django 4.0.1 on 2022-02-26 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_goods_desc_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['-id'], 'verbose_name': 'sku', 'verbose_name_plural': 'sku'},
        ),
    ]
